use agent_client_protocol::ElicitationSchema;
pub use agent_client_protocol::{
    ContentChunk, Plan, PlanEntry, PlanEntryPriority, PlanEntryStatus, SessionUpdate, ToolCall,
    ToolCallStatus, ToolCallUpdate, ToolCallUpdateFields, ToolKind as AcpToolKind,
};
pub use agentline_permission::PermissionDanger;
use serde::{Deserialize, Serialize};
use std::path::PathBuf;
use std::time::SystemTime;

/// External session id used to route ACP traffic. This is the
/// [Agent Client Protocol](https://agentclientprotocol.com) native `SessionId`
/// (a UUID-ish string), generated by the bridge on `new_session` and handed
/// back to clients. Distinct from [`AgentSessionId`], which is the underlying
/// agent-subprocess session.
pub use agent_client_protocol::SessionId;

/// ACP-native prompt content. A prompt is a sequence of these blocks (text,
/// image, audio, resource link, embedded resource). Re-exported so IM adapters
/// build prompts in the protocol's own vocabulary without depending on the
/// `agent_client_protocol` crate directly.
pub use agent_client_protocol::{ContentBlock, ResourceLink, TextContent};

/// Best-effort flatten of ACP content blocks into a single plain-text string.
/// Used by non-ACP backends (which only accept text) and for logging.
pub fn content_to_text(content: &[ContentBlock]) -> String {
    let mut parts: Vec<String> = Vec::new();
    for block in content {
        match block {
            ContentBlock::Text(t) => parts.push(t.text.clone()),
            ContentBlock::ResourceLink(r) => {
                parts.push(format!("[{}]({})", r.name, r.uri));
            }
            ContentBlock::Image(_) => parts.push("[image]".to_string()),
            ContentBlock::Audio(_) => parts.push("[audio]".to_string()),
            ContentBlock::Resource(_) => parts.push("[resource]".to_string()),
            _ => {}
        }
    }
    parts.join("\n")
}

/// Build a single-text-block prompt (the common case).
pub fn text_prompt(text: impl Into<String>) -> Vec<ContentBlock> {
    vec![ContentBlock::Text(TextContent::new(text.into()))]
}

/// Bridge-level operations. InputSources produce these from platform-specific
/// interactions (text commands, button clicks, CLI flags, JSON messages).
/// Bridge only receives and executes them — it never parses raw text.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Command {
    /// `/cd <path>` — with explicit path
    Cd(PathBuf),
    /// `/cd` — no argument, trigger interactive directory listing
    CdInteractive,
    /// `/new`
    New,
    /// `/close [#N]` — close (destroy) a session. `/stop` is an alias.
    Close(Option<u32>),
    /// `/cancel` — cancel the running prompt but keep the session alive.
    Cancel,
    /// `/agent [name]` — switch agent backend, or list available agents.
    Agent(Option<String>),
    /// `/sessions` — list active sessions.
    Sessions,
    /// `/yolo`
    Yolo,
    /// `/safe`
    Safe,
    /// `/help` or `/?`
    Help,
    /// Bare-token affirmative: `y`, `yes`, `是`, `好`.
    YesToken,
    /// Bare-token negative: `n`, `no`, `否`, `不`.
    NoToken,
    /// Session-level approval: `s`, `session`, `会话`.
    SessionApprove,
    /// Anything else — including unknown slash-commands which are forwarded
    /// to the agent as-is.
    Plain(String),
}

/// A project the agent can be directed to clone and develop.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Project {
    pub name: String,
    pub git_url: String,
}

/// Stable identifier for an agent session, returned by AgentBackend::new_session.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct AgentSessionId(pub String);

impl AgentSessionId {
    pub fn new(s: impl Into<String>) -> Self {
        Self(s.into())
    }
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl std::fmt::Display for AgentSessionId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

/// Identifies the IM-side counterpart of a conversation.
///
/// `opaque` carries platform-specific context (e.g. iLink's `context_token`)
/// that the bridge doesn't interpret but the IM adapter needs back when sending.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PeerRef {
    pub user_id: String,
    pub group_id: Option<String>,
    pub opaque: serde_json::Value,
}

/// Pre-parsed inbound message from any source (IM, ACP, CLI).
/// Sources parse their platform-specific format internally and produce this
/// bridge-level type. Bridge never sees raw IM message kinds.
#[derive(Debug, Clone)]
pub struct SourceMessage {
    pub peer: PeerRef,
    pub payload: InboundPayload,
    pub received_at: SystemTime,
}

/// One frame of progress from the agent during a prompt.
///
/// Streaming content (text, tool calls, plans, mode changes, session info) is
/// carried as the ACP-native [`SessionUpdate`] inside the `Session` variant.
/// Only agentline-specific control events get their own variants.
#[derive(Debug, Clone)]
pub enum AgentUpdate {
    /// ACP session update — streaming content forwarded as-is.
    Session(SessionUpdate),
    /// Agent needs user permission for an action.
    PermissionRequest {
        id: String,
        what: String,
        danger: PermissionDanger,
        tool_kind: ToolKind,
    },
    /// Agent is asking the user a question (ACP elicitation).
    ElicitInput {
        id: String,
        prompt: String,
        schema: Option<ElicitationSchema>,
    },
    Done,
    Error(String),
}

pub use agentline_permission::ToolKind;

pub use agent_client_protocol::ElicitationPropertySchema;
pub use agent_client_protocol::EnumOption;

// ── New types for the InputSource architecture ──────────────────────────

/// Parsed inbound payload: either a command or user content.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum InboundPayload {
    /// A command recognized by the InputSource (e.g. /yolo, button click, CLI flag).
    Command(Command),
    /// User content to be sent to the agent.
    Content(UserContent),
}

/// Composite user message: text + zero or more attachments.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserContent {
    pub text: Option<String>,
    pub attachments: Vec<Attachment>,
}

impl UserContent {
    pub fn text(s: impl Into<String>) -> Self {
        Self {
            text: Some(s.into()),
            attachments: Vec::new(),
        }
    }

    pub fn is_empty(&self) -> bool {
        self.text.as_ref().is_none_or(|t| t.is_empty()) && self.attachments.is_empty()
    }

    pub fn to_prompt_text(&self) -> String {
        let mut parts = Vec::new();
        if let Some(ref text) = self.text {
            parts.push(text.clone());
        }
        for att in &self.attachments {
            match att.kind {
                AttachmentKind::Image => {
                    parts.push(format!("![image]({})", att.local_path.display()));
                }
                AttachmentKind::Voice => {
                    if let Some(ref transcript) = att.transcript {
                        parts.push(transcript.clone());
                    } else {
                        parts.push(format!("[voice]({})", att.local_path.display()));
                    }
                }
                AttachmentKind::File => {
                    let name = att.name.as_deref().unwrap_or("file");
                    parts.push(format!("[file: {}]({})", name, att.local_path.display()));
                }
                AttachmentKind::Video => {
                    parts.push(format!("[video]({})", att.local_path.display()));
                }
            }
        }
        parts.join("\n")
    }

    pub fn to_content_blocks(&self) -> Vec<ContentBlock> {
        let mut blocks = Vec::new();
        if let Some(ref text) = self.text
            && !text.is_empty()
        {
            blocks.push(ContentBlock::Text(TextContent::new(text.clone())));
        }
        for att in &self.attachments {
            let uri = format!("file://{}", att.local_path.display());
            let name = match att.kind {
                AttachmentKind::Image => att.name.clone().unwrap_or_else(|| "image".into()),
                AttachmentKind::Voice => att.name.clone().unwrap_or_else(|| "voice".into()),
                AttachmentKind::File => att.name.clone().unwrap_or_else(|| "file".into()),
                AttachmentKind::Video => att.name.clone().unwrap_or_else(|| "video".into()),
            };
            blocks.push(ContentBlock::ResourceLink(ResourceLink::new(name, uri)));
            if let Some(ref transcript) = att.transcript {
                blocks.push(ContentBlock::Text(TextContent::new(transcript.clone())));
            }
        }
        if blocks.is_empty() {
            blocks.push(ContentBlock::Text(TextContent::new(String::new())));
        }
        blocks
    }
}

/// A single attachment in an inbound message.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Attachment {
    pub kind: AttachmentKind,
    /// Local path (InputSource downloads media before handing off to Bridge).
    pub local_path: PathBuf,
    /// Display name (for files).
    pub name: Option<String>,
    /// Voice-to-text transcript (for voice attachments).
    pub transcript: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AttachmentKind {
    Image,
    Voice,
    File,
    Video,
}

/// Inbound message with routing information (which InputSource it came from).
/// The payload is already parsed by the InputSource's `parse_message`.
#[derive(Debug, Clone)]
pub struct RoutedMessage {
    pub source_id: String,
    pub peer: PeerRef,
    pub payload: InboundPayload,
    pub received_at: std::time::SystemTime,
}

// ── Bridge atomic API result types ───────────────────────────────────

/// Result of `Bridge::set_mode()`.
#[derive(Debug, Clone)]
pub enum ModeResult {
    /// Mode applied to the active session.
    Applied { tag: String },
    /// No active session; mode will apply to the next session created.
    Pending,
    /// No active session (and mode cannot be deferred).
    NoSession,
}

/// Result of `Bridge::set_cwd()`.
#[derive(Debug, Clone)]
pub enum CwdResult {
    /// cwd changed, no session impact.
    Changed,
    /// cwd changed and the active session was closed because cwd differs.
    SessionClosed { tag: String },
    /// Path does not exist.
    NotFound,
    /// Path is not a directory.
    NotADir,
}

/// Result of `Bridge::prompt()`.
#[derive(Debug, Clone)]
pub enum PromptResult {
    /// Prompt dispatched immediately.
    Started,
    /// Another prompt is running; this one was queued.
    Queued { tag: String },
}

/// Result of `Bridge::respond_permission()`.
#[derive(Debug, Clone)]
pub enum PermissionResult {
    /// Permission was answered.
    Answered {
        effective: crate::permission::PermissionResponse,
    },
    /// No pending permission request.
    NoPending,
}

/// Snapshot of the current session for external display.
#[derive(Debug, Clone)]
pub struct SessionInfo {
    pub short_id: u32,
    pub session_id: String,
    pub agent_name: String,
    pub cwd: std::path::PathBuf,
    pub created_at: std::time::SystemTime,
    pub idle_duration: std::time::Duration,
    pub is_yolo: bool,
    pub grant_summary: String,
}

/// Parse user reply into a structured `serde_json::Value` based on the
/// elicitation schema. If schema carries selectable options, numeric input
/// is resolved to the corresponding option value.
pub fn parse_elicit_response(text: &str, schema: Option<&ElicitationSchema>) -> serde_json::Value {
    let text = text.trim();
    let Some(schema) = schema else {
        return serde_json::Value::String(text.to_string());
    };
    let Some((_, prop)) = schema.properties.iter().next() else {
        return serde_json::Value::String(text.to_string());
    };
    match prop {
        ElicitationPropertySchema::String(s) => {
            if let Some(options) = single_select_options(s)
                && let Ok(n) = text.parse::<usize>()
                && n >= 1
                && n <= options.len()
            {
                return serde_json::Value::String(options[n - 1].0.clone());
            }
            serde_json::Value::String(text.to_string())
        }
        ElicitationPropertySchema::Array(ms) => {
            let options = multi_select_options(&ms.items);
            let indices: Vec<usize> = text
                .split(',')
                .filter_map(|s| s.trim().parse::<usize>().ok())
                .collect();
            if !indices.is_empty() && indices.iter().all(|&i| i >= 1 && i <= options.len()) {
                let values: Vec<serde_json::Value> = indices
                    .iter()
                    .map(|&i| serde_json::Value::String(options[i - 1].0.clone()))
                    .collect();
                return serde_json::Value::Array(values);
            }
            serde_json::Value::String(text.to_string())
        }
        ElicitationPropertySchema::Boolean(_) => {
            let lower = text.to_lowercase();
            match lower.as_str() {
                "y" | "yes" | "true" | "是" | "1" => serde_json::Value::Bool(true),
                "n" | "no" | "false" | "否" | "0" => serde_json::Value::Bool(false),
                _ => serde_json::Value::String(text.to_string()),
            }
        }
        ElicitationPropertySchema::Number(_) | ElicitationPropertySchema::Integer(_) => {
            if let Ok(n) = text.parse::<f64>() {
                serde_json::Number::from_f64(n)
                    .map(serde_json::Value::Number)
                    .unwrap_or_else(|| serde_json::Value::String(text.to_string()))
            } else {
                serde_json::Value::String(text.to_string())
            }
        }
        _ => serde_json::Value::String(text.to_string()),
    }
}

/// Extract (value, label) pairs from a single-select string property.
pub fn single_select_options(
    s: &agent_client_protocol::StringPropertySchema,
) -> Option<Vec<(String, String)>> {
    if let Some(ref one_of) = s.one_of {
        let opts: Vec<(String, String)> = one_of
            .iter()
            .map(|o| (o.value.clone(), o.title.clone()))
            .collect();
        if !opts.is_empty() {
            return Some(opts);
        }
    }
    if let Some(ref values) = s.enum_values {
        let opts: Vec<(String, String)> = values.iter().map(|v| (v.clone(), v.clone())).collect();
        if !opts.is_empty() {
            return Some(opts);
        }
    }
    None
}

/// Extract (value, label) pairs from multi-select items.
pub fn multi_select_options(
    items: &agent_client_protocol::MultiSelectItems,
) -> Vec<(String, String)> {
    use agent_client_protocol::MultiSelectItems;
    match items {
        MultiSelectItems::Titled(t) => t
            .options
            .iter()
            .map(|o| (o.value.clone(), o.title.clone()))
            .collect(),
        MultiSelectItems::Untitled(u) => u
            .values
            .iter()
            .map(|v: &String| (v.clone(), v.clone()))
            .collect(),
        _ => Vec::new(),
    }
}
